# Generated by Django 3.0.5 on 2020-05-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
