# Generated by Django 3.0.7 on 2020-06-12 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField(default=0)),
                ('characters', models.IntegerField(default=0)),
                ('avg_cpm', models.IntegerField(default=0)),
                ('avg_wpm', models.IntegerField(null=True)),
                ('avg_accuracy', models.FloatField(null=True)),
                ('races', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
