# Generated by Django 3.0.6 on 2020-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='races',
            field=models.IntegerField(null=True),
        ),
    ]
