# Generated by Django 3.0.7 on 2020-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_lvl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
