# Generated by Django 3.0.7 on 2020-06-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200613_1113'),
        ('register', '0002_profile_training_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='training_lvl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Level'),
        ),
    ]
