# Generated by Django 3.0.6 on 2020-05-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200513_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_accuracy',
            field=models.FloatField(null=True),
        ),
    ]
