# Generated by Django 3.0.6 on 2020-05-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile_avg_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avg_speed',
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_wpm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='errors',
            field=models.IntegerField(null=True),
        ),
    ]
