# Generated by Django 3.0.7 on 2020-06-13 11:31

from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200613_1113'),
        ('register', '0003_auto_20200613_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='training_lvl',
            field=models.ForeignKey(default=register.models.get_training_lvl, on_delete=django.db.models.deletion.CASCADE, to='training.Level'),
        ),
    ]
