# Generated by Django 3.0.6 on 2020-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200513_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cpm',
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_cpm',
            field=models.FloatField(null=True),
        ),
    ]
