# Generated by Django 3.0.6 on 2020-05-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200513_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avg_cpm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avg_wpm',
        ),
        migrations.AddField(
            model_name='profile',
            name='characters',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='words',
            field=models.FloatField(null=True),
        ),
    ]
