# Generated by Django 3.0.6 on 2020-05-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200513_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_cpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_wpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='characters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='words',
            field=models.IntegerField(null=True),
        ),
    ]
