# Generated by Django 3.0.5 on 2020-05-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Osoba',
        ),
    ]
