# Generated by Django 3.0.7 on 2020-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.IntegerField()),
                ('max_err', models.IntegerField()),
                ('min_wpm', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
