# Generated by Django 3.0.7 on 2020-06-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_no',
            field=models.IntegerField(unique=True),
        ),
    ]
