# Generated by Django 3.0.7 on 2020-06-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200613_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='time',
            field=models.IntegerField(default=60),
        ),
    ]
