# Generated by Django 3.0.7 on 2020-06-14 00:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0003_level_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.IntegerField(default=0, null=True)),
                ('cpm', models.IntegerField(default=0, null=True)),
                ('errors', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
